{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Main.NoRequestService exposing (mtNoRequest)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.2.0
- `protoc` 4.22.2
- the following specification files: `alloptions.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.


@docs mtNoRequest
-}

import Grpc.Internal
import Proto.Main
import Proto.Nrpc


{-| A template for a gRPC call to the method 'MtNoRequest' sending a `NoRequest` to get back a `SimpleStringReply`.


-}
mtNoRequest : Grpc.Internal.Rpc Proto.Nrpc.NoRequest Proto.Main.SimpleStringReply
mtNoRequest =
    Grpc.Internal.Rpc
        { service = "NoRequestService"
        , package = "main"
        , rpcName = "MtNoRequest"
        , encoder = Proto.Nrpc.encodeNoRequest
        , decoder = Proto.Main.decodeSimpleStringReply
        }
