{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Main.SvcSubjectParams exposing (mtNoReply, mtNoRequestWParams, mtStreamedReplyWithSubjectParams, mtWithSubjectParams)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.2.0
- `protoc` 4.22.2
- the following specification files: `alloptions.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.


@docs mtNoReply, mtNoRequestWParams, mtStreamedReplyWithSubjectParams, mtWithSubjectParams
-}

import Grpc.Internal
import Proto.Main
import Proto.Nrpc


{-| A template for a gRPC call to the method 'MtNoRequestWParams' sending a `NoRequest` to get back a `SimpleStringReply`.


-}
mtNoRequestWParams : Grpc.Internal.Rpc Proto.Nrpc.NoRequest Proto.Main.SimpleStringReply
mtNoRequestWParams =
    Grpc.Internal.Rpc
        { service = "SvcSubjectParams"
        , package = "main"
        , rpcName = "MtNoRequestWParams"
        , encoder = Proto.Nrpc.encodeNoRequest
        , decoder = Proto.Main.decodeSimpleStringReply
        }


{-| A template for a gRPC call to the method 'MtNoReply' sending a `Void` to get back a `NoReply`.


-}
mtNoReply : Grpc.Internal.Rpc Proto.Nrpc.Void Proto.Nrpc.NoReply
mtNoReply =
    Grpc.Internal.Rpc
        { service = "SvcSubjectParams"
        , package = "main"
        , rpcName = "MtNoReply"
        , encoder = Proto.Nrpc.encodeVoid
        , decoder = Proto.Nrpc.decodeNoReply
        }


{-| A template for a gRPC call to the method 'MtStreamedReplyWithSubjectParams' sending a `Void` to get back a `SimpleStringReply`.


-}
mtStreamedReplyWithSubjectParams : Grpc.Internal.Rpc Proto.Nrpc.Void Proto.Main.SimpleStringReply
mtStreamedReplyWithSubjectParams =
    Grpc.Internal.Rpc
        { service = "SvcSubjectParams"
        , package = "main"
        , rpcName = "MtStreamedReplyWithSubjectParams"
        , encoder = Proto.Nrpc.encodeVoid
        , decoder = Proto.Main.decodeSimpleStringReply
        }


{-| A template for a gRPC call to the method 'MtWithSubjectParams' sending a `Void` to get back a `SimpleStringReply`.


-}
mtWithSubjectParams : Grpc.Internal.Rpc Proto.Nrpc.Void Proto.Main.SimpleStringReply
mtWithSubjectParams =
    Grpc.Internal.Rpc
        { service = "SvcSubjectParams"
        , package = "main"
        , rpcName = "MtWithSubjectParams"
        , encoder = Proto.Nrpc.encodeVoid
        , decoder = Proto.Main.decodeSimpleStringReply
        }
