module Nrpc.NrpcRpc exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM NATS COMPILER
-- https://github.com/nats-rpc/elm-nrpc
-- source file: nrpc/nrpc.proto

import Nats.Cmd
import Nats.Sub
import Nrpc

import Nrpc.Nrpc exposing (..)


pkgSubject : String
pkgSubject =
    "nrpc"


